# Stage 1: build
FROM golang:1.22-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/api1 .

# Stage 2: runtime
FROM alpine:3.22
WORKDIR /app
COPY --from=builder /app/api1 .
EXPOSE 8081
CMD ["./api1"]
