apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-writer
  template:
    metadata:
      labels:
        app: kafka-writer
    spec:
      containers:
        - name: kafka-writer
          image: registry.example.com/so1/kafka-writer:1.0   # Reemplaza con tu imagen Docker
          ports:
            - containerPort: 6001
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"  # Nombre del servicio Kafka dentro del clúster
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-writer
spec:
  selector:
    app: kafka-writer
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001
  type: ClusterIP
